### ISSUE TITLE
ZendAMF and Laravel 5

### ISSUE THREAD

**Issue by quinhone** [zendframework/ZendAmf#3]
Hello, I need to integrate ZendAMF with Laravel 5 that is compatible with 5? I would have documentation on how to integrate?

**Comment by Ocramius** [comment]
Just create a new [`Server`](https://github.com/zendframework/ZendAmf/blob/ac507493e7683acf5675bd0380c395c74d985c04/library/ZendAmf/Server.php#L28) (usually within your service definitions) and then use it from there.

Docs are at http://framework.zend.com/manual/1.12/en/zend.amf.html
